### ISSUE TITLE
Fetch swapi person on client-side

### ISSUE THREAD

**Issue by ibgrav** [hartdave/nextjs-todos#1]
https://github.com/hartdave/nextjs-todos/blob/5fba0853628b83ff65b205bafd1b089d034abc6d/pages/%5B%5B...slug%5D%5D.tsx#L5

The `/api/swapi` fetch should be done in the browser not the server
Move the fetch into your Footer component
You'll have to create state to hold the person data, then on mount fetch the data and update the state

**Comment by hartdave** [comment]
fixed
